<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityRepository;

/**
 * CommentaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaryRepository extends EntityRepository
{
    public function findActiveCommentary()
    {
        $expr = Criteria::expr();
        $criteria = Criteria::create();
        $criteria->where(
            $expr->lte('date', new \DateTime())
        );
        $criteria->orderBy(['date' => 'DESC']);
        return $this->matching($criteria);
    }
}
